# -*- coding: utf-8 -*-
"""modelling

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vt-5qNobteScFiHnBx0QlOTC7qS7woDl

# Membangun Model Machine Learning Basic

1. Import Library
"""

# Kriteria 2 basic

# Import Library
!pip install mlflow
import pandas as pd
import numpy as np
import os
import joblib
import matplotlib.pyplot as plt
import seaborn as sns
import mlflow
import mlflow.sklearn
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score
from sklearn.ensemble import RandomForestClassifier

"""2. Membuat path"""

# Tentukan nama folder
ARTIFACT_DIR = "artifacts"

# Tentukan path file di dalam folder tersebut
data_path = os.path.join(ARTIFACT_DIR, "social_media_mental_health_preprocessing.csv")

# Buat folder artifacts jika belum ada
os.makedirs(ARTIFACT_DIR, exist_ok=True)
experiment_name = "mental_health_classification_basic"

# Cetak informasi untuk memastikan
print(f"Direktori artifacts: {os.path.abspath(ARTIFACT_DIR)}")
print(f"Path data: {data_path}")

# Set MLflow
mlflow.set_experiment(experiment_name)

"""3.Loading dataset yang sudah dilakukan preprocessing"""

df = pd.read_csv(data_path)
df.head()

"""4. Membangun Model"""

# Memisahkan fitur dan target
X = df.drop(columns=['mental_state'])
y = df['mental_state']

# Split data train dan test
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
    )

# Melihat dimensi fitur dan target
print("Dimensi fitur")
print(f"X_train: {X_train.shape}")
print(f"X_test: {X_test.shape}")

# Menggunakan autolog
mlflow.sklearn.autolog()
with mlflow.start_run(run_name = "Random_Forest_Basic"):
    model = RandomForestClassifier(n_estimators=200, random_state=42)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    print(f"Accuracy: {accuracy:.4f}")
    report = classification_report(y_test, y_pred)
    print(report)

    # Menyimpan model
    model_path = os.path.join(ARTIFACT_DIR, "random_forest_basic.pkl")
    joblib.dump(model, model_path)
    print(f"Model saved to {model_path}")

print('Basic selesai')